<a href="https://colab.research.google.com/github/MuhammadAqsandy/PracticalLinearAlgebra/blob/main/05_Chapter05_Matrices_Part_1___Basics_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 05: Matrices Part 1 - Basics and Operations

**Topics Covered:**
- Matrix Creation
- Matrix Addition & Scalar Mult
- Matrix Multiplication
- Transpose
- Special Matrices


## Matrix Creation

In [2]:
import numpy as np

# Various ways to create matrices
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)
randon_m = np.random.randn(3, 3)
print('A:\n', A)
print('Identity:\n', identity)

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Matrix Addition & Scalar Multiplication

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print('A + B:\n', A + B)
print('A - B:\n', A - B)
print('3 * A:\n', 3 * A)

A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
3 * A:
 [[ 3  6]
 [ 9 12]]


## Matrix Multiplication

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
# Method 1: @
C1 = A @ B
# Method 2: np.matmul
C2 = np.matmul(A, B)
print('A @ B:\n', C1)
print('Note: A @ B != B @ A')
print('B @ A:\n', B @ A)

A @ B:
 [[19 22]
 [43 50]]
Note: A @ B != B @ A
B @ A:
 [[23 34]
 [31 46]]


## Transpose

In [5]:
A = np.array([[1,2,3],[4,5,6]])
print('A shape:', A.shape)
print('A.T shape:', A.T.shape)
print('A:\n', A)
print('A.T:\n', A.T)
# Symmetric matrix: A == A.T
S = np.array([[1,2],[2,4]])
print('Is symmetric:', np.allclose(S, S.T))

A shape: (2, 3)
A.T shape: (3, 2)
A:
 [[1 2 3]
 [4 5 6]]
A.T:
 [[1 4]
 [2 5]
 [3 6]]
Is symmetric: True


## Special Matrices

In [6]:
# Diagonal matrix
D = np.diag([1, 2, 3])
print('Diagonal:\n', D)
# Upper triangular
U = np.triu(np.ones((3,3)))
print('Upper triangular:\n', U)
# Lower triangular
L = np.tril(np.ones((3,3)))
print('Lower triangular:\n', L)

Diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Upper triangular:
 [[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
Lower triangular:
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## 📝 Summary

Chapter 5 introduces matrices as 2D arrays organizing data into rows and columns. Matrix addition is element-wise and requires same shapes, while matrix multiplication (the key operation) requires inner dimensions to match and is NOT commutative (AB ≠ BA in general). The transpose flips rows and columns, playing a critical role in computing covariance matrices and solving linear systems. Special matrices (identity, diagonal, triangular, symmetric) appear constantly in algorithms and have properties that simplify computations.