<a href="https://colab.research.google.com/github/MuhammadAqsandy/PracticalLinearAlgebra/blob/main/09_Chapter09_Orthogonal_Matrices_and_QR_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 09: Orthogonal Matrices and QR Decomposition

**Topics Covered:**
- Orthogonal Matrices
- Gram-Schmidt Process
- QR Decomposition
- Applications of QR
- Householder Reflections


## Orthogonal Matrix Properties

In [2]:
import numpy as np

# Orthogonal matrix: Q.T @ Q = I, det(Q) = ±1
theta = np.pi / 3
Q = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])
print('Q.T @ Q:\n', np.round(Q.T @ Q, 10))
print('det(Q):', round(np.linalg.det(Q), 10))
print('Orthogonal:', np.allclose(Q.T @ Q, np.eye(2)))

Q.T @ Q:
 [[ 1. -0.]
 [-0.  1.]]
det(Q): 1.0
Orthogonal: True


## Gram-Schmidt Orthogonalization

In [3]:
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        w = v.copy().astype(float)
        for b in basis:
            w -= np.dot(w, b) * b
        if np.linalg.norm(w) > 1e-10:
            basis.append(w / np.linalg.norm(w))
    return np.array(basis)

vectors = [np.array([1,1,0]), np.array([1,0,1]), np.array([0,1,1])]
Q = gram_schmidt(vectors)
print('Orthonormal basis:\n', np.round(Q, 4))
print('Q @ Q.T:\n', np.round(Q @ Q.T, 10))

Orthonormal basis:
 [[ 0.7071  0.7071  0.    ]
 [ 0.4082 -0.4082  0.8165]
 [-0.5774  0.5774  0.5774]]
Q @ Q.T:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


## QR Decomposition

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]], dtype=float)
Q, R = np.linalg.qr(A)
print('Q (orthogonal):\n', np.round(Q, 4))
print('R (upper triangular):\n', np.round(R, 4))
print('Q @ R = A?', np.allclose(Q @ R, A))

Q (orthogonal):
 [[-0.1231  0.9045  0.4082]
 [-0.4924  0.3015 -0.8165]
 [-0.8616 -0.3015  0.4082]]
R (upper triangular):
 [[ -8.124   -9.6011 -11.9399]
 [  0.       0.9045   1.5076]
 [  0.       0.       0.4082]]
Q @ R = A? True


## QR for Solving Linear Systems

In [5]:
A = np.array([[1,2],[3,4],[5,6]], dtype=float)
b = np.array([1,2,3], dtype=float)
Q, R = np.linalg.qr(A)
# Least squares via QR
Qtb = Q.T @ b
x = np.linalg.solve(R[:2,:], Qtb[:2])
print('Solution:', np.round(x, 4))
# Verify with lstsq
x_lstsq, _, _, _ = np.linalg.lstsq(A, b, rcond=None)
print('lstsq solution:', np.round(x_lstsq, 4))

Solution: [0.  0.5]
lstsq solution: [-0.   0.5]


## Check Orthonormality of Q

In [6]:
Q, R = np.linalg.qr(np.random.randn(4, 4))
print('Q.T @ Q:\n', np.round(Q.T @ Q, 8))
print('Is orthonormal:', np.allclose(Q.T @ Q, np.eye(4)))

Q.T @ Q:
 [[ 1.  0. -0.  0.]
 [ 0.  1. -0. -0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]
Is orthonormal: True


## 📝 Summary

Chapter 9 explores orthogonal matrices and QR decomposition. Orthogonal matrices preserve lengths and angles (think rotations/reflections) and have the convenient property that their inverse equals their transpose. The Gram-Schmidt process converts any set of linearly independent vectors into an orthonormal basis. QR decomposition factors any matrix into Q (orthogonal) and R (upper triangular), which is numerically stable and used for solving linear systems, computing eigenvalues, and least-squares fitting.