<a href="https://colab.research.google.com/github/MuhammadAqsandy/PracticalLinearAlgebra/blob/main/13_Chapter13_Eigendecomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 13: Eigendecomposition

**Topics Covered:**
- Eigenvalues & Eigenvectors
- Characteristic Polynomial
- Diagonalization
- Symmetric Matrix Eigendecomposition
- Power Iteration


## Computing Eigenvalues and Eigenvectors

In [2]:
import numpy as np
A = np.array([[4, 2],[1, 3]], dtype=float)
eigenvalues, eigenvectors = np.linalg.eig(A)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors (columns):\n', np.round(eigenvectors, 4))
# Verify: A @ v = λ * v
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]; v = eigenvectors[:,i]
    print(f'λ={lam:.2f}: A@v={np.round(A@v,4)}, λ*v={np.round(lam*v,4)}, match={np.allclose(A@v, lam*v)}')

Eigenvalues: [5. 2.]
Eigenvectors (columns):
 [[ 0.8944 -0.7071]
 [ 0.4472  0.7071]]
λ=5.00: A@v=[4.4721 2.2361], λ*v=[4.4721 2.2361], match=True
λ=2.00: A@v=[-1.4142  1.4142], λ*v=[-1.4142  1.4142], match=True


## Diagonalization: A = V D V^-1

In [4]:
A = np.array([[4,2],[1,3]], dtype=float)
# np.linalg.eig returns eigenvalues (1D array) and eigenvectors (2D array)
# Correct variable assignment for eigendecomposition A = V D V^-1
eigenvalues, V = np.linalg.eig(A) # V is now the eigenvector matrix

# D is the diagonal matrix of eigenvalues
D = np.diag(eigenvalues)

# Reconstruct A
A_recon = V @ D @ np.linalg.inv(V)
print('Original A:\n', A)
print('Reconstructed A:\n', np.round(A_recon, 6))

Original A:
 [[4. 2.]
 [1. 3.]]
Reconstructed A:
 [[4. 2.]
 [1. 3.]]


## Symmetric Matrix (Real Eigenvalues)

In [5]:
S = np.array([[4,2,0],[2,3,1],[0,1,2]], dtype=float)
eigvals, eigvecs = np.linalg.eigh(S)  # for symmetric
print('Eigenvalues (real):', np.round(eigvals, 4))
print('Eigenvectors orthogonal:', np.allclose(eigvecs.T @ eigvecs, np.eye(3)))

Eigenvalues (real): [0.8549 2.476  5.6691]
Eigenvectors orthogonal: True


## Power Iteration (Dominant Eigenvalue)

In [6]:
def power_iteration(A, num_iter=100):
    b = np.random.rand(A.shape[0])
    for _ in range(num_iter):
        b_new = A @ b
        b = b_new / np.linalg.norm(b_new)
    eigenvalue = (A @ b) @ b / (b @ b)
    return eigenvalue, b
A = np.array([[2,1],[1,3]], dtype=float)
lam, v = power_iteration(A)
print('Dominant eigenvalue:', round(lam, 6))
print('NumPy check:', round(max(np.linalg.eigvals(A)), 6))

Dominant eigenvalue: 3.618034
NumPy check: 3.618034


## Eigenvalues and Matrix Properties

In [7]:
A = np.array([[3,1],[1,3]], dtype=float)
eigvals = np.linalg.eigvals(A)
print('Eigenvalues:', eigvals)
print('Trace = sum of eigenvalues:', np.trace(A), '=', sum(eigvals))
print('Det = product of eigenvalues:', round(np.linalg.det(A),4), '=', round(np.prod(eigvals),4))

Eigenvalues: [4. 2.]
Trace = sum of eigenvalues: 6.0 = 6.0
Det = product of eigenvalues: 8.0 = 8.0


## 📝 Summary

Chapter 13 introduces eigendecomposition — one of the most important concepts in linear algebra. An eigenvector v of matrix A is a special vector that only scales (not rotates) when multiplied by A: Av = λv, where λ is the eigenvalue. Diagonalization A = VDV⁻¹ expresses a matrix as a product involving its eigenvectors, making powers and exponentials of matrices efficient. Symmetric matrices always have real eigenvalues and orthogonal eigenvectors (spectral theorem), making them especially useful. Eigenvalues encode key matrix properties: trace = Σλᵢ, determinant = Πλᵢ.